DEF INPUT PARAM p_acct   AS CHAR NO-UNDO.
DEF INPUT PARAM p_cusip  AS CHAR NO-UNDO.
DEF INPUT PARAM p_stl_dt AS CHAR NO-UNDO.
DEF INPUT PARAM p_qty    AS DEC  NO-UNDO.
DEF INPUT PARAM p_amt    AS DEC  NO-UNDO.
DEF OUTPUT PARAM p_error AS CHAR NO-UNDO.


RETURN "".


 

 

