DEF INPUT PARAM p_acct   AS CHAR NO-UNDO.
DEF INPUT PARAM p_cusip  AS CHAR NO-UNDO.
DEF INPUT PARAM p_stl_dt AS CHAR NO-UNDO.
DEF INPUT PARAM p_qty    AS DEC  NO-UNDO.
DEF INPUT PARAM p_amt    AS DEC  NO-UNDO.
DEF OUTPUT PARAM p_error AS CHAR NO-UNDO.



FIND FIRST mfclac NO-LOCK
  WHERE mfclac.acct = p_acct
  NO-ERROR.

FIND FIRST mfsc NO-LOCK
  WHERE mfsc.cusip = p_cusip
  NO-ERROR.


RETURN "".


 

 

